import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
// import { SessionProvider } from "next-auth/react";
// import NavBar from "@/components/navbar";
// import NavIcon from "@/components/navIcon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homely | Vacation rentals, cabins, beach houses, & more",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* <SessionProvider> */}
        {children}
        {/* </SessionProvider> */}
        {/* <div className="fixed -bottom-1 w-full lg:hidden md:hidden ">
          <NavBarBottom user={user} />
        </div> */}
        <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}
