import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer";
import NavBar from "@/components/navbar";
import NavIcon from "@/components/navIcon";
import { createServerComponentClient } from "@/lib/server";
import NavBarBottom from "@/components/navBarBottom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PEGASUS | Vacation rentals, cabins, beach houses, & more",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createServerComponentClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <NavBar user={user} />
        </div>
        <NavIcon />
        {children}
        <div className="fixed -bottom-1 w-full lg:hidden md:hidden ">
          <NavBarBottom user={user} />
        </div>
        <Toaster />
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
